from django.urls import path

from . import views

urlpatterns = [
    path("dashboard/", views.admin_dashboard, name="admin-dashboard"),
    path(
        "toggle-active/<int:user_id>/",
        views.admin_toggle_user_active,
        name="admin-toggle-active",
    ),
    path("make-admin/<int:user_id>/", views.admin_make_admin, name="admin-make-admin"),
    path(
        "remove-admin/<int:user_id>/",
        views.admin_remove_admin,
        name="admin-remove-admin",
    ),
    path("create-category/", views.admin_create_category, name="admin-create-category"),
    path(
        "edit-category/<int:category_id>/",
        views.admin_edit_category,
        name="admin-edit-category",
    ),
    path(
        "delete-category/<int:category_id>/",
        views.admin_delete_category,
        name="admin-delete-category",
    ),
    path("create-service/", views.admin_create_service, name="admin-create-service"),
    path(
        "delete-service/<int:service_id>/",
        views.admin_delete_service,
        name="admin-delete-service",
    ),
    path(
        "toggle-service/<int:service_id>/",
        views.admin_toggle_service,
        name="admin-toggle-service",
    ),
    path(
        "update-service/<int:service_id>/",
        views.admin_edit_service,
        name="admin-update-service",
    ),
    path(
        "service/<int:service_id>/items/",
        views.admin_manage_service_items,
        name="admin-manage-service-items",
    ),
    path(
        "service-item/create/",
        views.admin_create_service_item,
        name="admin-create-service-item",
    ),
    path(
        "service-item/<int:item_id>/update/",
        views.admin_update_service_item,
        name="admin-update-service-item",
    ),
    path(
        "service/<int:service_id>/add-item/",
        views.admin_add_service_item_mapping,
        name="admin-add-service-item-mapping",
    ),
    path(
        "service-item-mapping/<int:mapping_id>/update/",
        views.admin_update_service_item_mapping,
        name="admin-update-service-item-mapping",
    ),
    path(
        "service-item-mapping/<int:mapping_id>/remove/",
        views.admin_remove_service_item_mapping,
        name="admin-remove-service-item-mapping",
    ),
    path("user/<int:user_id>/", views.get_user_details, name="admin-user-details"),
    path(
        "update-tech-status/<int:user_id>/",
        views.admin_update_tech_status,
        name="admin-update-tech-status",
    ),
    path(
        "request/<int:job_request_id>/",
        views.admin_get_requested_service_details,
        name="admin-review-details",
    ),
    path(
        "request/<int:job_request_id>/mark-reviewed/",
        views.admin_mark_request_reviewed,
        name="admin-mark-reviewed",
    ),
    path(
        "request/<int:job_request_id>/assign-technician/",
        views.admin_assign_technician,
        name="admin-assign-technician",
    ),
    path(
        "request/<int:job_request_id>/convert-to-project/",
        views.admin_convert_to_project,
        name="admin-convert-to-project",
    ),
    path(
        "project/<int:project_id>/update-status/",
        views.admin_update_project_status,
        name="admin-update-project-status",
    ),
    path(
        "project/<int:project_id>/update-start-date/",
        views.admin_update_project_start_date,
        name="admin-update-project-start-date",
    ),
]
