# Generated by Django 5.2.11 on 2026-03-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('USER', 'User'), ('BUSINESS', 'Business'), ('ADMIN', 'Admin'), ('PROJECT', 'Project')], max_length=20),
        ),
    ]
