# Generated by Django 5.2.11 on 2026-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Default terms and conditions for invoices')),
            ],
            options={
                'verbose_name': 'Company Configuration',
            },
        ),
    ]
