# Generated by Django 5.2.11 on 2026-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_companyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='company_address',
            field=models.TextField(default='123 Main Street, Bengaluru, Karnataka, India'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_email',
            field=models.EmailField(default='noreply.url.ly@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_name',
            field=models.CharField(default='MLS - Micro Labor Services', max_length=255),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_phone',
            field=models.CharField(default='+91-9876543210', max_length=15),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='gst_number',
            field=models.CharField(default='29XXXXX1234X1Z5', help_text='GSTIN number for tax purposes', max_length=20),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='pan_number',
            field=models.CharField(default='ABCDE1234F', help_text='PAN number for tax purposes', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='Payment is due immediately upon project completion.', help_text='Default terms and conditions for invoices'),
        ),
    ]
