# Generated by Django 5.2.11 on 2026-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('job_created', 'Job Created'), ('technician_assigned', 'Technician Assigned'), ('job_completed', 'Job Completed'), ('job_reminder', 'Job Reminder'), ('new_request', 'New Request'), ('new_technician', 'New Technician'), ('pending_reminder', 'Pending Reminder')], max_length=50),
        ),
    ]
