# Generated by Django 5.2.11 on 2026-03-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='source_request',
            new_name='job_request',
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requests', to='services.service'),
        ),
    ]
