# Generated by Django 5.2.11 on 2026-03-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_source_request_project_job_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='is_project_completed',
            field=models.BooleanField(default=False),
        ),
    ]
