# Generated by Django 5.2.11 on 2026-03-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_jobrequest_is_project_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('Task', 'Task'), ('Material', 'Material'), ('Tool', 'Tool')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this item is optional for the service')),
                ('extra_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Additional cost for this item beyond the base price of the service', max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of items when displaying service details')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_included', to='services.serviceitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='services.service')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('service', 'item')},
            },
        ),
    ]
