# Generated by Django 5.2.11 on 2026-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_serviceitem_serviceitemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_items/'),
        ),
    ]
