# Generated by Django 5.2.11 on 2026-03-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0005_add_serviceitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExtraMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_extra_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"item_type": "Material"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_extra_materials",
                        to="services.serviceitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_materials",
                        to="services.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
