# Generated by Django 5.2.11 on 2026-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_projectitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending/Quoted'), ('SCHED', 'Scheduled'), ('ONGOING', 'In Progress'), ('PAYMENT_PENDING', 'Payment Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
