"""
Django settings for mls project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SOCIAL_AUTH_RAISE_EXCEPTIONS = False
LOGIN_URL = "a:login"
LOGOUT_REDIRECT_URL = "a:login"
LOGIN_REDIRECT_URL = "a:redirect-dashboard"
SOCIAL_AUTH_LOGIN_ERROR_URL = "a:login"
SOCIAL_AUTH_AUTHENTICATION_ERROR_URL = "a:login"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("GOOGLE_CLIENT_ID", cast=str)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("GOOGLE_CLIENT_SECRET", cast=str)
SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django_celery_results",
    "django_celery_beat",
    "social_django",
    "authentication",
    "services",
    "billing",
    "adminapp",
    "customerapp",
    "notification",
    "auditapp",
    "tailwind",
    "theme",
]

if DEBUG:
    INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "authentication.middleware.RoleRequiredMiddleware",
    "adminapp.middleware.BlockedUserMiddleware",
    "authentication.middleware.CustomSocialAuthExceptionMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "mls.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
                "notification.context_processors.unread_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "mls.wsgi.application"

AUTH_USER_MODEL = "authentication.User"

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)


TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = "C:\\Program Files\\nodejs\\npm.cmd"

if DEBUG:
    SITE_DOMAIN = "127.0.0.1:8000"
    PROTOCOL = "http"
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "eveline-correlatable-lonna.ngrok-free.dev",
    ]
else:
    SITE_DOMAIN = "url-ly.onrender.com"
    PROTOCOL = "https"
    ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default='url-ly.onrender.com')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_ENGINE = config("DATABASE_ENGINE", default="django.db.backends.sqlite3")

if DATABASE_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": config("DATABASE_NAME"),
            "USER": config("DATABASE_USER"),
            "PASSWORD": config("DATABASE_PASSWORD"),
            "HOST": config("DATABASE_HOST"),
            "PORT": config("DATABASE_PORT", cast=int),
        }
    }

CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL", default="redis://:mls_redis_secret_2026@localhost:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="django-db")
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"
CELERY_BEAT_SCHEDULE = {
    "remind-pending-work-daily": {
        "task": "notification.tasks.remind_pending_work",
        "schedule": 86400.0,  # every 24 hours (in seconds)
    },
}
CELERY_TASK_ROUTES = {
    "auditapp.tasks.*": {"queue": "audit_queue"},
    "notification.tasks.*": {"queue": "notification_queue"},
    "authentication.tasks.*": {"queue": "email_queue"},
    "billing.tasks.*": {"queue": "email_queue"},
}


EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
SUPPORT_EMAIL = config("SUPPORT_EMAIL")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ── Twilio SMS ──────────────────────────────────────────────────────
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER", default="")

# ── Web Push (VAPID) ────────────────────────────────────────────────
# Generate keys once with:  python -c "from pywebpush import webpush; from py_vapid import Vapid; v=Vapid(); v.generate_keys(); print(v.private_pem()); print(v.public_key)"
# Or: vapid --gen
VAPID_PUBLIC_KEY = config("VAPID_PUBLIC_KEY", cast=str).replace("\\n", "\n")  # type: ignore
VAPID_PRIVATE_KEY = config("VAPID_PRIVATE_KEY", cast=str).replace("\\n", "\n")  # type: ignore
VAPID_ADMIN_EMAIL = config("VAPID_ADMIN_EMAIL", default="admin@example.com")

# ── Razorpay Payment Gateway ─────────────────────────────────────────
RAZORPAY_KEY_ID = config("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET", default="")
RAZORPAY_WEBHOOK_SECRET = config("RAZORPAY_WEBHOOK_SECRET", default="")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "authentication.pipelines.check_user_not_blocked",
    "authentication.pipelines.get_or_create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "loggers": {
        "fontTools": {
            "level": "ERROR",
        },
        "weasyprint": {
            "level": "ERROR",
        },
    },
}
