# Generated by Django 5.2.11 on 2026-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_phone_verified_user_signup_method_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('TECH', 'Technician'), ('CUST', 'Customer')], max_length=10, null=True),
        ),
    ]
