# Generated by Django 5.2.11 on 2026-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_address_created_at_customerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
