# Generated by Django 5.2.11 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_email_verified_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', max_length=10),
        ),
    ]
