# Generated by Django 5.2.11 on 2026-04-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='project_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
