# Generated by Django 5.2.11 on 2026-04-03 07:37

import authentication.utils
import authentication.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customerprofile_project_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.utils.user_aadhar_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), authentication.validators.validate_image_size, authentication.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.utils.user_profile_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), authentication.validators.validate_image_size, authentication.validators.validate_image]),
        ),
    ]
